### ISSUE TITLE
Failed to create bucket due to Client-Side timeout

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1000]
Steps to repro:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-demo-large/6/console

Error message:

```
10:43:42 All nodes are healthy
10:43:42 Creating bucket index-bucket with RAM 23422
10:43:42 POST http://ec2-107-23-165-157.compute-1.amazonaws.com:8091/pools/default/buckets 202
10:43:42 Traceback (most recent call last):
10:43:42   File "libraries/provision/provision_cluster.py", line 143, in <module>
10:43:42     sync_gateway_config=sync_gateway_conf
10:43:42   File "libraries/provision/provision_cluster.py", line 55, in provision_cluster
10:43:42     sync_gateway_config=sync_gateway_config
10:43:42   File "/var/jenkins/workspace/sync-gateway-perf-demo-large/libraries/provision/install_sync_gateway.py", line 108, in install_sync_gateway
10:43:42     create_server_buckets(cluster_config, sync_gateway_config)
10:43:42   File "/var/jenkins/workspace/sync-gateway-perf-demo-large/libraries/provision/install_sync_gateway.py", line 170, in create_server_buckets
10:43:42     cb_server.create_buckets(bucket_names)
10:43:42   File "/var/jenkins/workspace/sync-gateway-perf-demo-large/keywords/couchbaseserver.py", line 238, in create_buckets
10:43:42     self.create_bucket(bucket_name, per_bucket_ram_mb)
10:43:42   File "/var/jenkins/workspace/sync-gateway-perf-demo-large/keywords/couchbaseserver.py", line 273, in create_bucket
10:43:42     bucket = Bucket("couchbase://{}/{}".format(self.host, name))
10:43:42   File "/var/jenkins/workspace/sync-gateway-perf-demo-large/venv/lib/python2.7/site-packages/couchbase/bucket.py", line 210, in __init__
10:43:42     self._do_ctor_connect()
10:43:42   File "/var/jenkins/workspace/sync-gateway-perf-demo-large/venv/lib/python2.7/site-packages/couchbase/bucket.py", line 219, in _do_ctor_connect
10:43:42     self._connect()
10:43:42 couchbase.exceptions._TimeoutError_0x17 (generated, catch TimeoutError): <RC=0x17[Client-Side timeout exceeded for operation. Inspect network conditions or increase the timeout], There was a problem while trying to send/receive your request over the network. This may be a result of a bad network or a misconfigured client or server, C Source=(src/bucket.c,759)>
```

**Comment by sethrosetter** [comment]
@tleyden Have you seen this since?

**Comment by tleyden** [comment]
Nope, not seeing it regularly
