### ISSUE TITLE
Mobile Server upgrade job is failing silently

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1081]
http://uberjenkins.sc.couchbase.com:8080/job/cen006-p0-mobileupgrade-serverupgrade-sg-cbliteios/586/console

The upgrade server to specified in the job apparently doesn't exist, yet the job still succeeds. 

I'm seeing this in the output.
```
======================================================================
ERROR: add_and_rebalance (newupgradetests.Upgrade_Utils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytests/newupgradetests.py", line 98, in add_and_rebalance
    self.operations(self.servers[:self.nodes_init])
  File "pytests/newupgradebasetest.py", line 195, in operations
    self._bucket_creation()
  File "pytests/basetestcase.py", line 547, in _bucket_creation
    self.cluster.create_default_bucket(default_params)
  File "lib/couchbase_helper/cluster.py", line 261, in create_default_bucket
    return _task.result(timeout)
  File "lib/tasks/future.py", line 160, in result
    return self.__get_result()
  File "lib/tasks/future.py", line 112, in __get_result
    raise self._exception
MemcachedError: Memcached error #32 'Auth error':  Auth failure for vbucket :0 to mc 172.23.105.98:11210
```

Any failure during setup should fail this test, but it does not appear to be the case. @andreibaranouski Can you take a look at this and make sure that the job fails for all steps that are expected to succeed?

**Comment by raghusarangapani** [comment]
I have switched stop-on-failure from false to true.

**Comment by raghusarangapani** [comment]
testrunner.py has this piece of code:

        if (result.failures or result.errors) and \
                TestInputSingleton.input.param("stop-on-failure", False):
            print "test fails, all of the following tests will be skipped!!!"
            break

**Comment by raghusarangapani** [comment]
In addition to the errors mentioned in the description, here are the errors testrunner encountered but not reported:

Ran 1 test in 93.946s
FAILED (errors=1)
summary so far suite newupgradetests.Upgrade_Utils , pass 0 , fail 1
failures so far...
newupgradetests.Upgrade_Utils.add_and_rebalance
testrunner logs, diags and results are available under /Users/mocha/jenkins/workspace/cen006-p0-mobileupgrade-serverupgrade-sg-cbliteios/testrunner/logs/testrunner-17-Mar-25_11-53-10/test_1
Run after suite setup for newupgradetests.Upgrade_Utils.add_and_rebalance

Since stop-on-failure was set to false, test proceeded.

**Comment by sethrosetter** [comment]
This is still happening. Reopening.
```
2017-04-21 11:11:39,242 - root - INFO - waiting for memcached bucket : default in 172.23.106.71 to accept set ops
2017-04-21 11:11:39,574 - root - INFO - creating direct client 172.23.105.98:11210 default
2017-04-21 11:11:39,737 - root - WARNING - unable to establish connection to 172.23.105.98. cleanup open connections
2017-04-21 11:11:39,739 - root - ERROR - Unexpected error: Memcached error #32 'Auth error':  Auth failure for vbucket :0 to mc 172.23.105.98:11210
2017-04-21 11:11:39,739 - root - WARNING - vbucket map not ready after try 4
2017-04-21 11:11:39,740 - root - INFO - waiting for memcached bucket : default in 172.23.106.71 to accept set ops
2017-04-21 11:11:40,076 - root - INFO - creating direct client 172.23.105.98:11210 default
2017-04-21 11:11:40,238 - root - WARNING - unable to establish connection to 172.23.105.98. cleanup open connections
2017-04-21 11:11:40,239 - root - ERROR - Unexpected error: Memcached error #32 'Auth error':  Auth failure for vbucket :0 to mc 172.23.105.98:11210
2017-04-21 11:11:40,239 - root - WARNING - vbucket map not ready after try 5
ERROR

======================================================================
ERROR: add_and_rebalance (newupgradetests.Upgrade_Utils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytests/newupgradetests.py", line 98, in add_and_rebalance
    self.operations(self.servers[:self.nodes_init])
  File "pytests/newupgradebasetest.py", line 195, in operations
    self._bucket_creation()
  File "pytests/basetestcase.py", line 554, in _bucket_creation
    self.cluster.create_default_bucket(default_params)
  File "lib/couchbase_helper/cluster.py", line 263, in create_default_bucket
    return _task.result(timeout)
  File "lib/tasks/future.py", line 160, in result
    return self.__get_result()
  File "lib/tasks/future.py", line 112, in __get_result
    raise self._exception
MemcachedError: Memcached error #32 'Auth error':  Auth failure for vbucket :0 to mc 172.23.105.98:11210

----------------------------------------------------------------------
Ran 1 test in 85.178s

FAILED (errors=1)
[('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py', 783, '__bootstrap', 'self.__bootstrap_inner()'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py', 810, '__bootstrap_inner', 'self.run()'), ('lib/tasks/taskmanager.py', 31, 'run', 'task.step(self)'), ('lib/tasks/task.py', 77, 'step', 'self.check(task_manager)'), ('lib/tasks/task.py', 320, 'check', 'self.set_exception(e)'), ('lib/tasks/future.py', 264, 'set_exception', 'print traceback.extract_stack()')]
Fri Apr 21 11:11:40 2017
[('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py', 783, '__bootstrap', 'self.__bootstrap_inner()'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py', 810, '__bootstrap_inner', 'self.run()'), ('testrunner.py', 291, 'run', '**self._Thread__kwargs)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/runner.py', 151, 'run', 'test(result)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py', 395, '__call__', 'return self.run(*args, **kwds)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py', 331, 'run', 'testMethod()'), ('pytests/newupgradetests.py', 98, 'add_and_rebalance', 'self.operations(self.servers[:self.nodes_init])'), ('pytests/newupgradebasetest.py', 195, 'operations', 'self._bucket_creation()'), ('pytests/basetestcase.py', 554, '_bucket_creation', 'self.cluster.create_default_bucket(default_params)'), ('lib/couchbase_helper/cluster.py', 263, 'create_default_bucket', 'return _task.result(timeout)'), ('lib/tasks/future.py', 160, 'result', 'return self.__get_result()'), ('lib/tasks/future.py', 111, '__get_result', 'print traceback.extract_stack()')]
teardown done
summary so far suite newupgradetests.Upgrade_Utils , pass 0 , fail 1
failures so far...
newupgradetests.Upgrade_Utils.add_and_rebalance
testrunner logs, diags and results are available under /Users/mocha/jenkins/workspace/cen006-p0-mobileupgrade-serverupgrade-sg-cbliteios/testrunner/logs/testrunner-17-Apr-21_11-10-14/test_1
test fails, all of the following tests will be skipped!!!
Run after suite setup for newupgradetests.Upgrade_Utils.add_and_rebalance
Thread Thread-40 was not properly terminated, will be terminated now.
Thread Thread-22 was not properly terminated, will be terminated now.
Thread Thread-46 was not properly terminated, will be terminated now.
```

Please get it to fail if it fails the job.

**Comment by raghusarangapani** [comment]
I've put in a small piece of code in the jenkins shell to catch this error and fail

**Comment by sethrosetter** [comment]
Its it missing error code failures? you could try a set -e (I think that is what it is ...) to fail immediately if any script fails?

**Comment by raghusarangapani** [comment]
Upon error, testrunner.py is printing it but not exiting with an error code as far as I can see, so jenkins thinks its a pass. I tee'd the output to a log file and specifically look for "test fails" string and 'exit 1' if it exists.

**Comment by sethrosetter** [comment]
Can you follow up someone more familiar with testrunner to see how they avoid this in a more general sense or is this what they do?
