### ISSUE TITLE
Current master branch SG configs not compatible with older SG version

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#1240]
Steps to repro:

```
python libraries/provision/provision_cluster.py \
    --sync-gateway-config-file=resources/sync_gateway_configs/sync_gateway_default_cc.json \
    --server-version 4.5.1 \
    --sync-gateway-version 1.3.1-16
```

Sync Gateway fails to startup, and panics with these errors:

```
2017-06-12T21:52:42.827Z ==== Couchbase Sync Gateway/1.3.1(16;f18e833) ====
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e78ea]

goroutine 1 [running]:
github.com/couchbase/sync_gateway/rest.(*ServerContext)._getOrAddDatabaseFromConfig(0xc82013ad80, 0xc82000c460, 0xc82013ad00, 0x15acc20, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:473 +0x1f9a
github.com/couchbase/sync_gateway/rest.(*ServerContext).getOrAddDatabaseFromConfig(0xc82013ad80, 0xc82000c460, 0x406a00, 0x0, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:254 +0xa4
github.com/couchbase/sync_gateway/rest.(*ServerContext).AddDatabaseFromConfig(0xc82013ad80, 0xc82000c460, 0xc8200fde40, 0x0, 0x0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.3.1/enterprise/godeps/src/github.com/couchbase/sync_gateway/rest/server_context.go:650 +0x3c
github.com/couchbase/sync_gateway/rest.RunServer(0xc8201386c0)
```

The workaround is to remove the following snippet from the sg config:

```
            {{ autoimport }}
            "unsupported": {
                {{ xattrs }}
            },
```

I also think Sync Gateway should be more robust in these cases and just emit a warning rather than panicking and failing to startup.  I will file a separate ticket for that.

**Comment by raghusarangapani** [comment]
This is a duplicate of https://github.com/couchbaselabs/mobile-testkit/issues/1225

**Comment by sethrosetter** [comment]
Yes. It is blowing up to due to the empty `"unsupported": {}` block. 1.4+ does not blow up . It we could get the handling backported to 1.3.1, that would be awesome.

**Comment by tleyden** [comment]
Closing in favor of https://github.com/couchbase/sync_gateway/issues/2689
