### ISSUE TITLE
README issue running virtualenv -p /usr/bin/python2.7 venv

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#449]
I ran `virtualenv -p /usr/bin/python2.7 venv` and got:

```
$ virtualenv -p /usr/bin/python2.7 venv
Running virtualenv with interpreter /usr/bin/python2.7
Overwriting /Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/orig-prefix.txt with new content
New python executable in /Users/tleyden/Development/mobile-testkit/venv/bin/python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 921, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1376, in install_python
    raise e
OSError: [Errno 62] Too many levels of symbolic links
```

**Comment by tleyden** [comment]
Ditto running `setup.sh`:

```
$ source setup.sh
Using Python version: 2.7.11
15.0.1
Running virtualenv with interpreter /usr/local/bin/python
Overwriting /Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/orig-prefix.txt with new content
New python executable in /Users/tleyden/Development/mobile-testkit/venv/bin/python2.7
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 921, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1214, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 62] Too many levels of symbolic links: '/Users/tleyden/Development/mobile-testkit/venv/bin/python2.7'
-bash: /Users/tleyden/Development/mobile-testkit/venv/bin/pip: /Users/tleyden/Development/mobile-testkit/venv/bin/python2.7: bad interpreter: Too many levels of symbolic links
```
