### ISSUE TITLE
More info needed when SG install fails

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#450]
I'm seeing this [SG install / build failure](http://uberjenkins.sc.couchbase.com:8080/view/QE%20Dev/job/syncgateway-functional-tests-dev/31/artifact/mobile-testkit/debug.txt):

```
 [WARNING]: Consider using git module rather than running git
Traceback (most recent call last):
  File "libraries/provision/provision_cluster.py", line 141, in <module>
    install_deps=opts.install_deps
  File "libraries/provision/provision_cluster.py", line 59, in provision_cluster
    install_sync_gateway.install_sync_gateway(sync_gateway_config)
  File "/var/jenkins/workspace/syncgateway-functional-tests-dev/mobile-testkit/libraries/provision/install_sync_gateway.py", line 103, in install_sync_gateway
    assert(status == 0)
AssertionError
```

How do I get more info on why SG failed to install?

Here is the relevant code:

```
def install_sync_gateway(sync_gateway_config):
    print(sync_gateway_config)

    if not sync_gateway_config.is_valid():
        print "Invalid sync_gateway provisioning configuration. Exiting ..."
        sys.exit(1)

    if sync_gateway_config.build_flags != "":
        print("\n\n!!! WARNING: You are building with flags: {} !!!\n\n".format(sync_gateway_config.build_flags))

    ansible_runner = AnsibleRunner()
    config_path = os.path.abspath(sync_gateway_config.config_path)

    if sync_gateway_config.commit is not None:
        # Install source
        status = ansible_runner.run_ansible_playbook(
            "install-sync-gateway-source.yml",
            "sync_gateway_config_filepath={0} commit={1} build_flags={2} skip_bucketflush={3}".format(
                config_path,
                sync_gateway_config.commit,
                sync_gateway_config.build_flags,
                sync_gateway_config.skip_bucketflush
            ),
            stop_on_fail=False
        )
        assert(status == 0)
```

**Comment by tleyden** [comment]
Nevermind, was in the logs, but hard to find

**Comment by tleyden** [comment]
if you ever run into this error (running as root) when running `sync_gateway_service_install.sh`:

```
systemctl enable sync_gateway
Failed to execute operation: Access denied
```

this workaround that worked for me is:

```
systemctl daemon-reload
```

as documented here: http://serverfault.com/questions/684342/systemctl-throwing-errors-on-start-enable-after-package-instal
