### ISSUE TITLE
Run perf sanity for sync_gateway 1.3.1

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#622]
Run same tests as run for [1.3.0](https://github.com/couchbase/sync_gateway/issues/1910)

**Comment by sethrosetter** [comment]
Need to sync of with @tleyden for knowledge transfer

**Comment by tleyden** [comment]
To generate graphs: https://github.com/couchbaselabs/mobile-testkit/blob/master/libraries/utilities/analyze_perf_results.py

**Comment by tleyden** [comment]
Upgrading the http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/ jenkins job to call `install_deps.py`

**Comment by tleyden** [comment]
In this job http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/103/console I ran into this error:

```
16:36:59 TASK [DEPS | update clock] *****************************************************
16:37:00 failed: [ma5]
16:37:00 fatal: [ma5]: FAILED! => {"changed": true, "cmd": "ntpdate 0.us.pool.ntp.org", "delta": "0:00:00.218292", "end": "2016-08-31 16:37:00.209643", "failed": true, "rc": 1, "start": "2016-08-31 16:36:59.991351", "stderr": "31 Aug 16:37:00 ntpdate[11216]: the NTP socket is in use, exiting", "stdout": "", "stdout_lines": [], "warnings": []}
16:37:00 failed: [ma3]
16:37:00 fatal: [ma3]: FAILED! => {"changed": true, "cmd": "ntpdate 0.us.pool.ntp.org", "delta": "0:00:00.236463", "end": "2016-08-31 16:37:00.209112", "failed": true, "rc": 1, "start": "2016-08-31 16:36:59.972649", "stderr": "31 Aug 16:37:00 ntpdate[5255]: the NTP socket is in use, exiting", "stdout": "", "stdout_lines": [], "warnings": []}
16:37:00 failed: [ma4]
```

**Comment by tleyden** [comment]
http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/104/ failed due to gateload not starting

**Comment by tleyden** [comment]
The perf run completed: http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/105/

However I'm having trouble running `analyze_perf_results.py`.  If I try under virtualenv, after running `source setup.sh`, I'm getting:

```
$ python libraries/utilities/analyze_perf_results.py
Traceback (most recent call last):
  File "libraries/utilities/analyze_perf_results.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

Which is a known issue documented in https://github.com/couchbaselabs/mobile-testkit/issues/569

If I try it outside of virtualenv, eg, **not** running `source setup.sh`, I'm getting:

```
$ python libraries/utilities/analyze_perf_results.py
Traceback (most recent call last):
  File "libraries/utilities/analyze_perf_results.py", line 5, in <module>
    import matplotlib
ImportError: No module named matplotlib
```

**Comment by tleyden** [comment]
I ran `pip install matplotlib` and now I'm getting a different error:

```
tleyden_macbook:mobile-testkit tleyden$ python libraries/utilities/analyze_perf_results.py --help
Traceback (most recent call last):
  File "libraries/utilities/analyze_perf_results.py", line 10, in <module>
    from utilities.provisioning_config_parser import hosts_for_tag
ImportError: No module named utilities.provisioning_config_parser
```

**Comment by tleyden** [comment]
Opened `setup.sh` and commented:

```
#virtualenv -p python venv
#source venv/bin/activate
```

and re-ran, now getting:

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/rsa-3.4.2.dist-info/DESCRIPTION.rst'
```

Changed permissions:

```
pushd /usr/local/lib/python2.7/site-packages
sudo chown -R tleyden *
```

Now getting new error:

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/troposphere-1.4.0-py2.7.egg-info/dependency_links.txt'
```

Try to fix via:

```
 cd /Library/Python/2.7/site-packages/
sudo chown -R tleyden:admin .
```

Now getting

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/bin/cfn'
```

Fix via `sudo mv /usr/local/bin/cfn /tmp`, now `source setup.sh` on hacked setup.sh works!

And `analyze_perf_results.py` works:

```
$ python libraries/utilities/analyze_perf_results.py --help
Usage: analyze_perf_results.py
    --test-id=<test-id>


Options:
  -h, --help         show this help message and exit
  --test-id=TEST_ID  Test id to generate graphs for
```

**Comment by tleyden** [comment]
I found performance results I had stored previously on my local filesystem:

```
$ tree /Users/tleyden/Development/mobile-testkit/testsuites/syncgateway/performance/results/2_2016-07-01-20-02-46
testsuites/syncgateway/performance/results/2_2016-07-01-20-02-46
├── 2_2016-07-01-20-02-46-sglogs.zip
├── 2sg_3cbs_2lgs
├── gateload_expvars.json
├── gateload_expvars.png
├── lg1.json
├── lg2.json
├── perf_logs
│   ├── sg1
│   │   └── cpu_stats.json
│   └── sg2
│       └── cpu_stats.json
├── sync_gateway_expvars.json
├── sync_gateway_expvars.png
├── sync_gateway_machine_stats.png
└── sync_gateway_profile
    ├── sg1
    │   └── sync_gateway_profile.tar.gz
    └── sg2
        └── sync_gateway_profile.tar.gz

6 directories, 13 files
```

and was able to render png graphs by running:

```
$ python libraries/utilities/analyze_perf_results.py --test-id=2_2016-07-01-20-02-46
```

**Comment by tleyden** [comment]
To fetch the latest zip from [perf run 105](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/105/), I'm doing the following:

* `ssh root@s61701cnt72.sc.couchbase.com`
* `cd /var/jenkins/workspace/sync-gateway-performance-test/testsuites/syncgateway/performance/results`
* `tar cvfz 2_2016-08-31-18-06-47.tar.gz 2_2016-08-31-18-06-47`
* `scp root@s61701cnt72.sc.couchbase.com:/var/jenkins/workspace/sync-gateway-performance-test/testsuites/syncgateway/performance/results/2_2016-08-31-18-06-47.tar.gz /Users/tleyden/Development/mobile-testkit/testsuites/syncgateway/performance/results/`
* `pushd /Users/tleyden/Development/mobile-testkit/testsuites/syncgateway/performance/results/`
* `tar xvfz 2_2016-08-31-18-06-47.tar.gz`

Process via:

```
python libraries/utilities/analyze_perf_results.py --test-id=2_2016-08-31-18-06-47
```

**Comment by tleyden** [comment]
Results from [jenksin run 105](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-performance-test/105/)

* SG 1.3.1-16
* Couchbase Server 4.5.0
* 1k/1k

![gateload_expvars](https://cloud.githubusercontent.com/assets/296876/18185585/38577220-7053-11e6-8bc5-25ab3d52288d.png)

![sync_gateway_expvars](https://cloud.githubusercontent.com/assets/296876/18185588/3b50d52a-7053-11e6-93d0-0dfc8ba0d121.png)

![sync_gateway_machine_stats](https://cloud.githubusercontent.com/assets/296876/18185594/436cfa9a-7053-11e6-818b-1c6ab32d496d.png)
