### ISSUE TITLE
ansible.errors.AnsibleParserError provisioning on vagrant

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#646]
To reproduce:

* Run locally on OSX using vagrant
* Run `python libraries/provision/install_deps.py` <-- works
* Run `python libraries/provision/provision_cluster.py --server-version=4.1.1 --sync-gateway-commit=96e6e4927dfd648b153022b2f83665a967445167`

Error:

```
TASK [debug] *******************************************************************
ok: [cb1]
ok: [cb1] => {
    "msg": "Couchbase bucket RAM 480"
}
TASK [COUCHBASE SERVER | Create new buckets] ----------------------------------------------

TASK [COUCHBASE SERVER | Create new buckets] ***********************************
changed: [cb1] => (item=data-bucket)
changed: [cb1] => (item=index-bucket)
ok: [cb1]

PLAY RECAP *********************************************************************
cb1                        : ok=8    changed=1    unreachable=0    failed=0

>>> Waiting for server to be in 'healthy' state
GET http://192.168.33.10:8091/pools/nodes 200

  sync_gateway configuration
  ------------------------------------------
  version:          None
  build number:     None
  commit:           96e6e4927dfd648b153022b2f83665a967445167
  config path:      /Users/tleyden/Development/mobile-testkit/resources/sync_gateway_configs/sync_gateway_default.json
  build flags:
  skip bucketflush: False

Running playbook: libraries/provision/ansible/playbooks/install-sync-gateway-source.yml
Traceback (most recent call last):
  File "libraries/provision/provision_cluster.py", line 139, in <module>
    sync_gateway_config=sync_gateway_config
  File "libraries/provision/provision_cluster.py", line 52, in provision_cluster
    install_sync_gateway.install_sync_gateway(sync_gateway_config)
  File "/Users/tleyden/Development/mobile-testkit/libraries/provision/install_sync_gateway.py", line 99, in install_sync_gateway
    "skip_bucketflush": sync_gateway_config.skip_bucketflush
  File "/Users/tleyden/Development/mobile-testkit/libraries/provision/ansible_runner.py", line 27, in run_ansible_playbook
    stats = runner.run()
  File "/Users/tleyden/Development/mobile-testkit/libraries/provision/ansible_python_runner.py", line 139, in run
    self.pbex.run()
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 73, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 53, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 98, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/play.py", line 115, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/play.py", line 167, in _load_tasks
    return load_list_of_blocks(ds=ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 58, in load_list_of_blocks
    loader=loader
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/block.py", line 79, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/block.py", line 115, in _load_block
    use_handlers=self._use_handlers,
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 244, in load_list_of_tasks
    t = Task.load(task_ds, block=block, role=role, task_include=task_include, variable_manager=variable_manager, loader=loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/task.py", line 135, in load
    return t.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/base.py", line 195, in load_data
    ds = self.preprocess_data(ds)
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/ansible/playbook/task.py", line 177, in preprocess_data
    raise AnsibleParserError(to_str(e), obj=ds)
ansible.errors.AnsibleParserError: this task 'file' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/Users/tleyden/Development/mobile-testkit/libraries/provision/ansible/playbooks/install-sync-gateway-source.yml': line 98, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  # Create target directory and deploy binary
  - name: SG ACCEL | Creates /opt/couchbase-sg-accel
    ^ here


The error appears to have been in '/Users/tleyden/Development/mobile-testkit/libraries/provision/ansible/playbooks/install-sync-gateway-source.yml': line 98, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  # Create target directory and deploy binary
  - name: SG ACCEL | Creates /opt/couchbase-sg-accel
    ^ here
```

**Comment by tleyden** [comment]
Full output: https://gist.github.com/tleyden/f51f3afde637420ebd1e97a4a81c6840

**Comment by tleyden** [comment]
If I provision using a binary package it works: https://gist.github.com/tleyden/6119fdd502e39158fa8f7d47df46eff2

**Comment by sethrosetter** [comment]
@tleyden Are you on latest master (testkit)? I fixed a bug a couple days ago that looks similar to this.

**Comment by tleyden** [comment]
Yup on commit https://github.com/couchbaselabs/mobile-testkit/commit/eb744a31c017fab03bf742ce181c1ef838f05032

**Comment by tleyden** [comment]
@sethrosetter the fact that it works w/ binaries but not building SG from source seems to indicate that it's specific to that ansible playbook

**Comment by sethrosetter** [comment]
@tleyden Is this still an issue?
