### ISSUE TITLE
Provisioning error 400 Client Error: Bad Request for url:

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#709]
This is on the strip-robot branch .. provisioning on AWS via:

```
python libraries/provision/provision_cluster.py --server-version 4.5.0 --sync-gateway-version 1.3.1-16
```

Getting error:

```
>>> Waiting for server to be in 'healthy' state
{u'load_generators': [{u'ip': u'ec2-54-166-60-190.compute-1.amazonaws.com', u'name': u'lg1'}], u'couchbase_servers': [{u'ip': u'ec2-54-172-168-29.compute-1.amazonaws.com', u'name': u'cb1'}, {u'ip': u'ec2-54-174-108-179.compute-1.amazonaws.com', u'name': u'cb2'}, {u'ip': u'ec2-54-165-178-169.compute-1.amazonaws.com', u'name': u'cb3'}], u'sync_gateways': [{u'ip': u'ec2-54-164-42-81.compute-1.amazonaws.com', u'name': u'sg1'}, {u'ip': u'ec2-54-172-68-104.compute-1.amazonaws.com', u'name': u'sg2'}, {u'ip': u'ec2-54-172-10-45.compute-1.amazonaws.com', u'name': u'sg3'}], u'hosts': [{u'ip': u'ec2-54-172-168-29.compute-1.amazonaws.com', u'name': u'host1'}, {u'ip': u'ec2-54-174-108-179.compute-1.amazonaws.com', u'name': u'host2'}, {u'ip': u'ec2-54-165-178-169.compute-1.amazonaws.com', u'name': u'host3'}, {u'ip': u'ec2-54-164-42-81.compute-1.amazonaws.com', u'name': u'host4'}, {u'ip': u'ec2-54-172-68-104.compute-1.amazonaws.com', u'name': u'host5'}, {u'ip': u'ec2-54-172-10-45.compute-1.amazonaws.com', u'name': u'host6'}, {u'ip': u'ec2-52-91-248-42.compute-1.amazonaws.com', u'name': u'host7'}, {u'ip': u'ec2-54-166-60-190.compute-1.amazonaws.com', u'name': u'host8'}], u'load_balancers': [], u'sg_accels': [{u'ip': u'ec2-52-91-248-42.compute-1.amazonaws.com', u'name': u'ac1'}]}
GET http://ec2-54-172-168-29.compute-1.amazonaws.com:8091/pools/nodes 200
All nodes are healthy
Installing Sync Gateway

  sync_gateway configuration
  ------------------------------------------
  version:          1.3.1
  build number:     16
  commit:           None
  config path:      /Users/tleyden/Development/mobile-testkit/resources/sync_gateway_configs/sync_gateway_default.json
  build flags:
  skip bucketcreation: False

{u'load_generators': [{u'ip': u'ec2-54-166-60-190.compute-1.amazonaws.com', u'name': u'lg1'}], u'couchbase_servers': [{u'ip': u'ec2-54-172-168-29.compute-1.amazonaws.com', u'name': u'cb1'}, {u'ip': u'ec2-54-174-108-179.compute-1.amazonaws.com', u'name': u'cb2'}, {u'ip': u'ec2-54-165-178-169.compute-1.amazonaws.com', u'name': u'cb3'}], u'sync_gateways': [{u'ip': u'ec2-54-164-42-81.compute-1.amazonaws.com', u'name': u'sg1'}, {u'ip': u'ec2-54-172-68-104.compute-1.amazonaws.com', u'name': u'sg2'}, {u'ip': u'ec2-54-172-10-45.compute-1.amazonaws.com', u'name': u'sg3'}], u'hosts': [{u'ip': u'ec2-54-172-168-29.compute-1.amazonaws.com', u'name': u'host1'}, {u'ip': u'ec2-54-174-108-179.compute-1.amazonaws.com', u'name': u'host2'}, {u'ip': u'ec2-54-165-178-169.compute-1.amazonaws.com', u'name': u'host3'}, {u'ip': u'ec2-54-164-42-81.compute-1.amazonaws.com', u'name': u'host4'}, {u'ip': u'ec2-54-172-68-104.compute-1.amazonaws.com', u'name': u'host5'}, {u'ip': u'ec2-54-172-10-45.compute-1.amazonaws.com', u'name': u'host6'}, {u'ip': u'ec2-52-91-248-42.compute-1.amazonaws.com', u'name': u'host7'}, {u'ip': u'ec2-54-166-60-190.compute-1.amazonaws.com', u'name': u'host8'}], u'load_balancers': [], u'sg_accels': [{u'ip': u'ec2-52-91-248-42.compute-1.amazonaws.com', u'name': u'ac1'}]}
GET http://ec2-54-172-168-29.compute-1.amazonaws.com:8091/pools/default/buckets 200
Existing buckets: []
Deleting buckets: []
Creating buckets: [u'data-bucket', u'index-bucket']
total_avail_ram_mb: 0 effective_avail_ram_mb: -512 effective_avail_ram_mb: -512
Create bucket data-bucket with per_bucket_ram_mb -256
POST http://ec2-54-172-168-29.compute-1.amazonaws.com:8091/pools/default/buckets 400
Traceback (most recent call last):
  File "libraries/provision/provision_cluster.py", line 136, in <module>
    sync_gateway_config=sync_gateway_conf
  File "libraries/provision/provision_cluster.py", line 54, in provision_cluster
    sync_gateway_config=sync_gateway_config
  File "/Users/tleyden/Development/mobile-testkit/libraries/provision/install_sync_gateway.py", line 106, in install_sync_gateway
    create_server_buckets(os.environ["CLUSTER_CONFIG"], sync_gateway_config)
  File "/Users/tleyden/Development/mobile-testkit/libraries/provision/install_sync_gateway.py", line 160, in create_server_buckets
    server_helper.create_buckets(couchbase_server_url, bucket_names)
  File "/Users/tleyden/Development/mobile-testkit/keywords/CouchbaseServer.py", line 205, in create_buckets
    self.create_bucket(url, bucket_name, per_bucket_ram_mb)
  File "/Users/tleyden/Development/mobile-testkit/keywords/CouchbaseServer.py", line 231, in create_bucket
    resp.raise_for_status()
  File "/Users/tleyden/Development/mobile-testkit/venv/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://ec2-54-172-168-29.compute-1.amazonaws.com:8091/pools/default/buckets
```

**Comment by tleyden** [comment]
Somehow it got negative values for ram ..

```
total_avail_ram_mb: 0 effective_avail_ram_mb: -512 effective_avail_ram_mb: -512
Create bucket data-bucket with per_bucket_ram_mb -256
```

**Comment by tleyden** [comment]
In the json returned from couchbase server, the mem_total is actually being reported as 0 for the first node: https://gist.github.com/tleyden/97ce746e432f56a7511968a8b36f6ada  (sorry about formatting)
