### ISSUE TITLE
Cannot install SG Accel from source

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#721]
To repro:

```
$ python libraries/provision/provision_cluster.py --server-version 4.5.0 
   --sync-gateway-commit 82493418e365495a2d23955fd62cccd71c60f5e3
```

Getting error:

```
TASK [Copy sg_accel binary to /opt/] *******************************************
fatal: [ac1]: FAILED! => {"changed": true, "cmd": "cp /home/centos/godeps/bin/sg_accel /opt/couchbase-sg-accel/bin/", "delta": "0:00:00.049475", "end": "2016-10-04 19:15:30.148268", "failed": true, "rc": 1, "start": "2016-10-04 19:15:30.098793", "stderr": "cp: cannot stat ‘/home/centos/godeps/bin/sg_accel’: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @libraries/provision/ansible/playbooks/install-sync-gateway-source.retry

PLAY RECAP *********************************************************************
ac1                        : ok=27   changed=12   unreachable=0    failed=1
cb1                        : ok=1    changed=0    unreachable=0    failed=0
cb2                        : ok=1    changed=0    unreachable=0    failed=0
cb3                        : ok=1    changed=0    unreachable=0    failed=0
sg1                        : ok=28   changed=13   unreachable=0    failed=0
sg2                        : ok=28   changed=13   unreachable=0    failed=0
sg3                        : ok=28   changed=13   unreachable=0    failed=0

Traceback (most recent call last):
  File "libraries/provision/provision_cluster.py", line 136, in <module>
    sync_gateway_config=sync_gateway_conf
  File "libraries/provision/provision_cluster.py", line 54, in provision_cluster
    sync_gateway_config=sync_gateway_config
  File "/Users/tleyden/Development/mobile-testkit/libraries/provision/install_sync_gateway.py", line 120, in install_sync_gateway
    raise ProvisioningError("Failed to install sync_gateway source")
keywords.exceptions.ProvisioningError: Failed to install sync_gateway source
```

**Comment by tleyden** [comment]
Blocked on https://github.com/couchbase/sync_gateway/issues/2115

**Comment by tleyden** [comment]
Note to self ..

This works:

`<remote fetch="ssh://git@github.com/couchbaselabs/" name="couchbaselabs_private" />`

This doesn't:

` <remote fetch="ssh://git@github.com:couchbaselabs/" name="couchbaselabs_private" />`

**Comment by tleyden** [comment]
Attempted re-run: http://uberjenkins.sc.couchbase.com/view/QE%20Dev/job/syncgateway-functional-tests-dev/158/

**Comment by tleyden** [comment]
It's failing because of github credentials on being on the VM.

To reproduce, run local vagrant cluster with mobile-testkit, then:

```
$ python libraries/provision/provision_cluster.py --server-version=4.5.0 --sync-gateway-commit=1cf0399c4d1f7593178706366cffba300821844f
```

and it will just hang.

when I ssh'd into the vm and tried to run the bootstrap.sh script manually, it prompted for a password and got stuck there:

```
[root@localhost centos]# ./bootstrap.sh
Fetching project npipe
Fetching project walrus
Fetching projects:   5% (2/37)  Fetching project blance
Fetching projects:   8% (3/37)  Fetching project net
Fetching projects:  10% (4/37)  Fetching project go-systemd
Fetching projects:  13% (5/37)  Fetching project sync-gateway-accel
Username for 'https://github.com':
```

To fix this, we'll have to do some more work about github key handling.

**Comment by tleyden** [comment]
https://github.com/couchbase/sync_gateway/commit/c9b351efcd03373383a3f3bf5c66a85ec680a5ad might fix this.  Retesting

**Comment by tleyden** [comment]
Nope, still broken, now on a different error:

```
Fetching projects:  13% (5/37)  Fetching project sync-gateway-accel
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by tleyden** [comment]
Steps:

- [ ] Create new *read-only* SSH keypair
- [ ] Put on S3 in `cbmobile-sharedkeys/cbmobile_private_repo_read_only`
- [ ] Add as deploy key to sync-gateway-accel repo under settings
- [ ] Write script to deploy the private key from "runner" (eg, jenkins runner or local machine if running locally)

**Comment by tleyden** [comment]
Script testing:

```
ssh vagrant@192.168.33.11 "sudo cp /tmp/cbmobile_private_repo_read_only /root/.ssh/id_rsa"
ssh vagrant@192.168.33.11 "sudo ssh-keyscan -t rsa github.com | sudo tee /root/.ssh/known_hosts"
ssh vagrant@192.168.33.11 "sudo git clone git@github.com:couchbaselabs/sync-gateway-accel.git"
```

**Comment by tleyden** [comment]
Got past those, new error:

```
TASK [SYNC GATEWAY | Install sg_accell service] ********************************
fatal: [ac2]: FAILED! => {"changed": true, "cmd": "./sg_accel_service_install.sh", "delta": "0:00:00.047639", "end": "2016-10-07 11:24:30.705065", "failed": true, "rc": 1, "start": "2016-10-07 11:24:30.657426", "stderr": "The sg_accel executable does not exist \"/opt/couchbase-sg-accel/bin/sg_accel\".", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [ac1]: FAILED! => {"changed": true, "cmd": "./sg_accel_service_install.sh", "delta": "0:00:00.049833", "end": "2016-10-07 11:24:30.660061", "failed": true, "rc": 1, "start": "2016-10-07 11:24:30.610228", "stderr": "The sg_accel executable does not exist \"/opt/couchbase-sg-accel/bin/sg_accel\".", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by tleyden** [comment]
Everything works on https://github.com/couchbaselabs/mobile-testkit/tree/feature/build-sg-accel2, but blocked on https://github.com/couchbase/sync_gateway/issues/2142

**Comment by tleyden** [comment]
One bad thing about this change: if you don't run

```
$ python libraries/utilities/install-gh-deploy-keys.py --key-path=/Users/tleyden/tmp/cbmobile_private_repo_read_only --ssh-user=vagrant
```

then running `libraries/provision/install_sync_gateway.py` will hang forever, because on the VM's the `bootstrap.sh` will be stuck on this prompt:

```
[root@localhost centos]# ./bootstrap.sh -p sg-accel
Fetching project npipe
Fetching project walrus
Fetching projects:   5% (2/37)  Fetching project blance
Fetching projects:   8% (3/37)  Fetching project net
Fetching projects:  10% (4/37)  Fetching project go-systemd
Fetching projects:  13% (5/37)  Fetching project sync-gateway-accel
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? ^Caborted by user
```

I wish there was a way to tell the `repo` tool to abort if it runs into: `Are you sure you want to continue connecting (yes/no)?`

**Comment by tleyden** [comment]
From @ceejatec 

> I've hit that on new machines too, and I don't know a way to fix it inside repo. (There may BE a way, but I don't know it.) If you're scripting in Ansible anyway, I'd suggest ensuring that an earlier step in your playbook sets things up for repo. Either take the brute force approach of putting a .ssh/known_hosts file in place, or maybe there's a way to invoke ssh with an "accept host key" option first?

**Comment by tleyden** [comment]
Functional test in progress:

http://uberjenkins.sc.couchbase.com/job/syncgateway-functional-tests-dev/170/console

**Comment by tleyden** [comment]
@ajres have you ever seen this error?

```
16:01:17 TASK [SYNC GATEWAY | Install sg_accell service] ********************************
16:01:17 fatal: [ac1]: FAILED! => {"changed": true, "cmd": "./sg_accel_service_install.sh", "delta": "0:00:00.076560", "end": "2016-10-11 16:01:17.522862", "failed": true, "rc": 1, "start": "2016-10-11 16:01:17.446302", "stderr": "Failed to execute operation: Access denied", "stdout": "", "stdout_lines": [], "warnings": []}
```

I'm running into it on this [jenkins job](http://uberjenkins.sc.couchbase.com/job/syncgateway-functional-tests-dev/173/console) 

and I think we should fix it before this PR gets merged:

https://github.com/couchbaselabs/mobile-testkit/pull/733

Have tried several workarounds including calling `systemctl daemon-reload` in the ansible script, but nothing seems to work.  Note on the the command line, calling `systemctl daemon-reload` seems to work, eg:

```
$ systemctl enabled sync_gateway
access denied error
$ systemctl daemon-reload
$ systemctl enabled sync_gateway
```

^^ that gets rid of the access denied error

Also, do you have any tips on how to debug this or get a better idea of what's causing it?

**Comment by tleyden** [comment]
According to this, it might be related to SELinux http://microdevsys.com/wp/failed-to-execute-operation-access-denied/

**Comment by tleyden** [comment]
Also possibly related:

* https://major.io/2015/09/18/systemd-in-fedora-22-failed-to-restart-service-access-denied/
* https://bugzilla.redhat.com/show_bug.cgi?id=1224211

**Comment by tleyden** [comment]
Disabling SELinux fixed the issue:

http://uberjenkins.sc.couchbase.com/job/syncgateway-functional-tests-dev/180/console

I updated the Jenkins job to add a checkbox for running INSTALL_DEPS, which disables SELinux by default
