### ISSUE TITLE
sgload run failed with read: connection reset by peer

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#742]
http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/31/consoleFull

```
10:51:00 t=2016-10-14T10:43:17-0700 lvl=info msg="Wait until writers finish"
10:51:00 t=2016-10-14T10:43:59-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[reason:Invalid doc/rev ID in _bulk_get status:400 error:bad_request id:]"
10:51:00 t=2016-10-14T10:43:59-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:43:59-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:44:00-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:44:00-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 t=2016-10-14T10:44:01-0700 lvl=warn msg="Document missing created_at field" doc.Body="map[error:bad_request id: reason:Invalid doc/rev ID in _bulk_get status:400]"
10:51:00 
10:51:00 2016/10/14 10:43:16 glNumReaders: 100
10:51:00 panic: Error performing update: Post http://s61705cnt72.sc.couchbase.com:4984/db/_bulk_docs: read tcp 172.23.108.88:19154->172.23.108.83:4984: read: connection reset by peer
10:51:00 
10:51:00 goroutine 857 [running]:
10:51:00 github.com/couchbaselabs/sgload/sgload.(*Updater).Run(0xc82007c090)
10:51:00 	/opt/go/src/github.com/couchbaselabs/sgload/sgload/updater.go:89 +0xa86
10:51:00 created by github.com/couchbaselabs/sgload/sgload.GateLoadRunner.startUpdaters
10:51:00 	/opt/go/src/github.com/couchbaselabs/sgload/sgload/gateload_runner.go:161 +0x3e4
```

**Comment by tleyden** [comment]
Moved to https://github.com/couchbaselabs/sgload/issues/11
