### ISSUE TITLE
Fix bucket deletion in node jobs

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#825]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by sethrosetter** [comment]
now seeing 
```
Running Server Version: 4.6.0-3567
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "keywords/CouchbaseServer.py", line 71, in __init__
    self.remote_executor = RemoteExecutor(self.host)
  File "keywords/RemoteExecutor.py", line 26, in __init__
    self.username = ansible.constants.DEFAULT_REMOTE_USER
AttributeError: 'module' object has no attribute 'constants'
```
