### ISSUE TITLE
ProvisioningError: Failed to install Couchbase Server

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#834]
In [sg perf run 201](http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/201/console) I got this error:

```
17:14:49 TASK [COUCHBASE SERVER | Join additional cluster nodes] ************************
17:14:49 skipping: [cb1]
17:14:49 fatal: [cb2]: FAILED! => {"changed": true, "cmd": "/opt/couchbase/bin/couchbase-cli server-add -c s61702cnt72.sc.couchbase.com:8091 --user=Administrator --password=password --server-add=s61703cnt72.sc.couchbase.com:8091 --server-add-username=Administrator --server-add-password=password", "delta": "0:00:00.157909", "end": "2016-12-21 17:14:49.899151", "failed": true, "rc": 2, "start": "2016-12-21 17:14:49.741242", "stderr": "", "stdout": "ERROR: unable to server-add s61703cnt72.sc.couchbase.com:8091 (400) Bad Request\n[\"Adding nodes to not provisioned nodes is not allowed.\"]", "stdout_lines": ["ERROR: unable to server-add s61703cnt72.sc.couchbase.com:8091 (400) Bad Request", "[\"Adding nodes to not provisioned nodes is not allowed.\"]"], "warnings": []}
17:14:49 fatal: [cb3]: FAILED! => {"changed": true, "cmd": "/opt/couchbase/bin/couchbase-cli server-add -c s61702cnt72.sc.couchbase.com:8091 --user=Administrator --password=password --server-add=s61704cnt72.sc.couchbase.com:8091 --server-add-username=Administrator --server-add-password=password", "delta": "0:00:00.147363", "end": "2016-12-21 17:14:49.896622", "failed": true, "rc": 2, "start": "2016-12-21 17:14:49.749259", "stderr": "", "stdout": "ERROR: unable to server-add s61704cnt72.sc.couchbase.com:8091 (400) Bad Request\n[\"Adding nodes to not provisioned nodes is not allowed.\"]", "stdout_lines": ["ERROR: unable to server-add s61704cnt72.sc.couchbase.com:8091 (400) Bad Request", "[\"Adding nodes to not provisioned nodes is not allowed.\"]"], "warnings": []}
17:14:49 
17:14:49 NO MORE HOSTS LEFT *************************************************************
17:14:49 	to retry, use: --limit @libraries/provision/ansible/playbooks/install-couchbase-server-package.retry
17:14:49 
17:14:49 PLAY RECAP *********************************************************************
17:14:49 cb1                        : ok=25   changed=6    unreachable=0    failed=0   
17:14:49 cb2                        : ok=25   changed=6    unreachable=0    failed=1   
17:14:49 cb3                        : ok=25   changed=6    unreachable=0    failed=1   
17:14:49 
17:14:49 Traceback (most recent call last):
17:14:49   File "libraries/provision/provision_cluster.py", line 147, in <module>
17:14:49     sync_gateway_config=sync_gateway_conf
17:14:49   File "libraries/provision/provision_cluster.py", line 47, in provision_cluster
17:14:49     couchbase_server_config=couchbase_server_config
17:14:49   File "/var/jenkins/workspace/sync-gateway-perf-test/libraries/provision/install_couchbase_server.py", line 146, in install_couchbase_server
17:14:49     raise ProvisioningError("Failed to install Couchbase Server")
17:14:49 keywords.exceptions.ProvisioningError: Failed to install Couchbase Server
17:14:49 Build step 'Execute shell' marked build as failure
```

Not sure if this is a sporadic thing or due to a code change.  Will retry.

**Comment by tleyden** [comment]
Looks like it was just a sporadic thing:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/202/console  

got paste that error

**Comment by sethrosetter** [comment]
I haven't seen that one before. Looks like a sporadic issue.

**Comment by sethrosetter** [comment]
Closing this as I have not seen this for a while
